@host = http://localhost:5191

GET {{host}}/weatherforecast/
Accept: application/json

###
@AdminId = "3fa85f64-5717-4562-b3fc-2c963f66afa6"
POST {{host}}/subscriptions
Content-Type: application/json

{
    "subscriptionType": "Free",
    "adminId": {{AdminId}}
}
###
GET {{host}}/subscriptions