@host = https://localhost:44311

GET {{host}}/weatherforecast/
Accept: application/json

###
@AdminId = "3fa85f64-5717-4562-b3fc-2c963f66afa6"
POST {{host}}/subscriptions
Content-Type: application/json

{
    "subscriptionType": "Premium",
    "adminId": {{AdminId}}
}
###
GET {{host}}/subscriptions/383137b0-1d9b-418c-b23c-0f0d8ab81463